[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# replace STM32F429ZITx with your chip as listed in `probe-rs chip list`
# runner = "probe-rs run --chip STM32F429ZITx"
runner = "arm-none-eabi-gdb -q -x openocd.gdb"

[build]
# target = "thumbv7em-none-eabi"
target = "thumbv7em-none-eabihf"     # Cortex-M4F and Cortex-M7F (with FPU)

[env]
DEFMT_LOG = "trace"
